import { AppProps } from 'next/app';
import Head from 'next/head';
import React, { ReactNode } from 'react'; // Add this import
import "../styles/style.scss";

function MyApp({ Component, pageProps }: AppProps): ReactNode { // Adjust the return type
  return (
    <>
      <Head>
        <title>Xtreme Starter Next Js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>

      {/* <FullLayout> */}
      <Component {...pageProps} />
      {/* </FullLayout> */}
    </>
  );
}

export default MyApp;